# -*- coding: utf-8 -*-
"""Untitled5.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gQROQLO561mLrf2hEryG_dqCkRddHXdp
"""

import numpy as np

def generate_table():
    x_values = np.linspace(0, np.pi*2, 1000)
    y_values = np.sin(x_values)
    values = np.column_stack((x_values, y_values))
    return values

def print_table(values):
    print("x\t\t\t\tsin(x)")
    print("-----------------------------------------------------")
    for x, y in values:
        print(f"{x}\t\t{y}")

def main():
    table_values = generate_table()
    print_table(table_values)

if __name__ == "__main__":
    main()